version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt

# no manual zip in ‘build’ phase at all
artifacts:
  # point to your project root
  base-directory: .  
  files:
    - '**/*'      # include everything
  discard-paths: no  # preserve subfolders